// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class accomodationpackage_entity_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accomodationpackage_entity_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202004130523573_accomodationpackage_entity_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
